name: Stats Card Generate

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: stats/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./stats
          publish_branch: stats
