name: Update Assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v6
    
      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@f9d8133845f40d659a754f78b8484983ba766448
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: assets/stats.svg
          token: ${{ secrets.READ_REPO_STATUS }}

      - name: Generate snake
        uses: Platane/snk/svg-only@d8f6715049803e982ee5ff501b6b9b7d5deeb09b
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets
          git commit -m "Update README assets"
          git push
